# Configurations
title: Σπουδαία websites!
longtitle: Φτιάξε σπουδαία sites, νίκησε τους γίγαντες του διαδικτύου!
author: Giorgos Katsiampas
email: katsampukas@gmail.com
description: >
  Ξεχώρισε από εκατομμύρια αποτελέσματα. Νίκησε τους γίγαντες του internet!

version: 1.0
gitbook_version: 3.2.3

url: 'https://greatwebsites.gr'
baseurl: ''
rss: RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

destination: ./docs
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jemoji
